### ISSUE TITLE
Help - Docs

### ISSUE THREAD

**Issue by ayoubensalem** [koalalorenzo/python-digitalocean#255] opened 2018-09-11 18:59 UTC
This is some really good library :+1:  , yet it lacks docs. 
To help yourself, refer to digital ocean api to get things done quickly : https://developers.digitalocean.com/documentation/v2

**Comment by koalalorenzo** [comment] 2018-10-25 19:55
It has a lot of docs but those are inline :) Sorry I am closing this issue as the Docs of the API should work fine by design, but I am not maintaining that much anymore.

**Closed by koalalorenzo** 2018-10-25 19:55 UTC
